Statistic
kurgan64/otus-cpp-basic pull request #9
Opened 2024-02-15 18:05 UTC by kurgan64

2024-02-16 18:24 UTC, MarinaPaley requested changes

2024-02-16 18:24 UTC, MarinaPaley commented on statistics/mean_std.h
> +    if (!count) return 0;
В данном случае не намного больше кода писать, а код будет понятнее, без неявных преобразований
`count == 0`

2024-02-16 18:24 UTC, MarinaPaley commented on statistics/mean_std.h
> +class Std : public IStatistics {
Почему не в отдельном файле?

2024-02-16 18:24 UTC, MarinaPaley commented on statistics/mean_std.h
> +    Mean mean;
`Mean mean{};`

2024-02-16 18:24 UTC, MarinaPaley commented on statistics/pct90_95.h
> +double calc_pct(const std::vector<double> &vec, const double percent);
Вы уже почти поняли, что необходим базовый метод...так точно не нужно)

2024-02-16 18:24 UTC, MarinaPaley commented on statistics/pct90_95.h
> +  if (frac_part == 0.0) return vec.at(int_part - 1);
Нельзя сравнивать тип `double` (любой тип с плавающей точкой) на строгое равенство или неравенство!

2024-02-16 18:24 UTC, MarinaPaley commented on statistics/mean_std.h
> +  mutable std::vector<double> vec;
Из-за того, что Вы сделали так, вызывая два раза метод `eval`, получаем на одном и том же наборе данных, разные ответы, что неправильно.
https://replit.com/@MarinaPaley/PolyMorfy#main.cpp
![image](https://github.com/kurgan64/otus-cpp-basic/assets/26978698/bc6809d4-fa00-45ad-b868-3f5d8414dec8)

2024-02-16 18:24 UTC, MarinaPaley commented on statistics/mean_std.h
> +  int count = 0;
если `m_sum`, почему `count` не `m_count`?

2024-02-16 18:24 UTC, MarinaPaley commented on statistics/pct90_95.h
> +  if (frac_part == 0.0) return vec.at(int_part - 1);
Нельзя сравнивать вещественный тип данных на строгое равенство (или неравенство)!

2024-02-18 12:20 UTC, MarinaPaley requested changes
Небольшие замечания

2024-02-18 12:20 UTC, MarinaPaley commented on statistics/pct.h
> +    double x, int_part, frac_part;
Не нужно объявлять заранее переменные, тем более неинициализированные.

2024-02-18 12:20 UTC, MarinaPaley commented on statistics/pct.h
> +  std::string p_name;
Обычно, чтобы явно сказать, что это член класс, поля называют `m_имя`, где `m` &ndash; `member`.
Но Вы в праве называть так, как считаете нужным.

2024-02-18 12:20 UTC, MarinaPaley commented on statistics/pct.h
> +#include "iostream"
Вы подключаете заголовочный файл [`<iostream>`](https://en.cppreference.com/w/cpp/header/iostream), хотя хотите &ndash; [`<string>`](https://en.cppreference.com/w/cpp/header/string), чтобы использовать функцию [`std::to_string`](https://en.cppreference.com/w/cpp/string/basic_string/to_string).

У Вас получается собрать код без ошибок (в этой части), потому что `<iostream>` транзитивно подключает `<string>`.

### `gcc`
[`<iostream>`](https://en.cppreference.com/w/cpp/header/iostream) &rarr; [`<ios>`](https://github.com/gcc-mirror/gcc/blob/master/libstdc%2B%2B-v3/include/std/ios) &rarr; [`<bits/ios_base.h>`](https://github.com/gcc-mirror/gcc/blob/master/libstdc%2B%2B-v3/include/bits/ios_base.h) &rarr; [`<bits/locale_classes.h>`](https://github.com/gcc-mirror/gcc/blob/master/libstdc%2B%2B-v3/include/bits/locale_classes.h) &rarr; [`<string>`](https://en.cppreference.com/w/cpp/header/string)

### `clang`
[`<iostream>`](https://en.cppreference.com/w/cpp/header/iostream) &rarr; [`<ios>`](https://github.com/llvm-mirror/libcxx/blob/master/include/ios) &rarr; [`<__locale>`](https://github.com/llvm-mirror/libcxx/blob/78d6a7767ed57b50122a161b91f59f19c9bd0d19/include/__locale) &rarr; [`<string>`](https://en.cppreference.com/w/cpp/header/string)

### `microsoft/STL`
Это странное название символизирует `cl.exe`. Тут граф выходит довольно сложный, и если честно, то мне его лень раскручивать полностью...

[`<iostream>`](https://github.com/microsoft/STL/blob/main/stl/inc/iostream) &rarr; [`<istream>`](https://github.com/microsoft/STL/blob/main/stl/inc/istream) &rarr; [`<ostream>`](https://github.com/microsoft/STL/blob/main/stl/inc/ostream) &rarr; [`<ios>`](https://github.com/microsoft/STL/blob/main/stl/inc/ios) &rarr; `...` &rarr; [`<string>`](https://en.cppreference.com/w/cpp/header/string)

2024-02-18 12:20 UTC, MarinaPaley commented on statistics/pct.h
> +    std::sort(p_vec.begin(), p_vec.end());
Без явного подключения заголовочного файла [`<algorithm>`](https://en.cppreference.com/w/cpp/header/algorithm) вызов функции [`std::sort`](https://en.cppreference.com/w/cpp/algorithm/sort) приведёт к ошибке времени компиляции как минимум для [`clang 12.0.1`](https://releases.llvm.org/12.0.1/tools/clang/docs/index.html).
```
In file included from ./main.cpp:2:
./pct.h:25:14: error: no member named 'sort' in namespace 'std'
        std::sort(p_vec.begin(), p_vec.end());
        ~~~~~^
```

2024-02-18 12:20 UTC, MarinaPaley commented on statistics/pct.h
> +  Pct() = delete;
Зачем, если объявлен конструктор с параметрами, то конструктор без параметров не будет создан компилятором.

2024-02-18 12:20 UTC, MarinaPaley commented on statistics/pct.h
> +  Pct(int percent) : p_percent(percent) { p_name = "pct" + std::to_string(p_percent); }
СтОит проверять, что процент меньше 100, иначе выбрасывать ошибку.
Можно все поля инициализировать, что является лучшим подходом, чем через присвоение (оператор присваивания может быть не переопределен, явно запрещен и т.д.). Тогда придется поменять последовательность полей в классе, так как объект создается именно в этом порядке, несмотря на порядок аргументов в конструкторе.

2024-02-18 19:16 UTC, kurgan64 commented on statistics/pct.h
> +  std::string p_name;
спасибо. Буду знать

2024-02-18 19:17 UTC, kurgan64 commented on statistics/pct.h
> +#include "iostream"
Если честно это был копипаст из наброска. линтер не поругался, а я и не заметил

2024-02-18 19:52 UTC, kurgan64 commented on statistics/pct.h
> +  std::string p_name;
я сначала подумал, что назвали так в честь имени класс Min - m_

2024-02-18 20:00 UTC, kurgan64 commented on statistics/pct.h
> +  Pct(int percent) : p_percent(percent) { p_name = "pct" + std::to_string(p_percent); }
**Можно все поля инициализировать, что является лучшим подходом, чем через присвоение (оператор присваивания может быть не переопределен, явно запрещен и т.д.). Тогда придется поменять последовательность полей в классе, так как объект создается именно в этом порядке, несмотря на порядок аргументов в конструкторе.** 
Очень ценный комментарий. я читал про это, но особого значения этому не придал. И очень странно ощущение, когда читаешь чей то код, то этого не замечаешь. А вот указали, и стало понятней.

2024-02-25 17:16 UTC, MarinaPaley approved these changes
Все отлично! Спасибо)

2024-02-25 17:22 UTC, merged